const mockEvents =
{
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1600085521000,
      duration: 7200000,
      id: '273247944',
      name: 'Online Meet-up: 1:1 Customer Engagement',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1603875600000,
      local_date: '2020-10-28',
      local_time: '10:00',
      updated: 1600085521000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26493437,
        name: 'DATACADEMY MUC online',
        lat: 48.13512420654297,
        lon: 11.58198070526123,
        repinned: false,
        address_1: 'RSVP -> siehe Eventbeschreibung links',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1552681092000,
        name: 'Munich DATACADEMY',
        id: 31398167,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Datacademy',
        who: 'DATACADEMISTs',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Datacademy/events/273247944/',
      description: '<p>Seien Sie live dabei und diskutieren Sie mit, wenn Branchenexperten, Fach- und Führungskräfte sich im Talkshow-Format über echte digitale Transformation und erfolgreiche Umsetzung austauschen.</p> <p>Schnelle Innovation ist die DNA einer erfolgreichen digitalen Transformation. Um mit dem heutigen, immer vernetzteren Kunden mithalten zu können, benötigen Unternehmen die richtige Strategie und Technologie. Ihre Kunden erwarten ein außergewöhnliches Kundenerlebnis - auf jedem Kanal und zu jeder Zeit. Diese Disziplin lässt sich nur mit nutzerzentrierten Innovationen in der Kundeninteraktion und der Prozessautomatisierung über verschiedene Funktionsbereiche hinweg beherrschen.</p> <p>Erhalten Sie wertvolle Impulse zu folgenden Aspekten:<br/>- Nutzen Sie Lösungen für eine schnelllebige Welt, um schnell neue Strategien umsetzen zu können<br/>- Setzen Sie auf proaktive Kundenbindung durch überzeugende, persönliche Angebote<br/>- Verkaufen Sie mit Fingerspitzengefühl, indem Sie Ihren Kunden auch in schwierigen Zeiten immer das anbieten, was sie brauchen</p> <p>Erleben Sie in diesem Online-Meet-up Case-Studies von Branchenführern aus erster Hand, spannende Diskussionen zu zukunftsfähigen Kundeninteraktionsstrategien und stellen den Referenten direkte Fragen.</p> <p>Gemeinsam mit unseren Kunden arbeiten wir an der digitalen Welt von morgen und an einer Lösung, wie wir unsere Mitarbeiter und Kunden in diesem Wandel bestmöglich unterstützen können. Dabei treiben wir die digitale Transformation mit führenden Organisationen, wie Siemens, Deutsche Telekom, Deutsche Bahn, DAK, Ferring, Roche, Erste Group... voran.</p> <p>Z. B. implementierte Siemens Pega als Standardplattform für Prozess- und digitales Case-Management mit dem Ziel einer globalen End-to-End-Digitalisierung. Ein paar Ergebnisse:<br/>- Effizienzverbesserung um 80-90%<br/>- Ein Zehntel der Kosten bei 10-facher Geschwindigkeit und unendlicher Skalierbarkeit<br/>-[masked] Benutzer weltweit</p> <p>Wir freuen uns auf Ihre Teilnahme!</p> <p>Anmeldung unter: <a href="http://bit.ly/pega2810" class="linkified">http://bit.ly/pega2810</a></p> ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1600839816000,
      duration: 7200000,
      id: '273447631',
      name: 'PowerShell Usergroup #region Munich October meetup',
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1602781200000,
      local_date: '2020-10-15',
      local_time: '19:00',
      updated: 1600839816000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 28,
      is_online_event: false,
      group: {
        created: 1478545915000,
        name: 'German PowerShell Usergroup',
        id: 21077231,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'German-PowerShell-Usergroup',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/German-PowerShell-Usergroup/events/273447631/',
      description: '<p>#region MeetUp<br/><a href="https://github.com/GPSUG/Munich" class="linkified">https://github.com/GPSUG/Munich</a></p> <p>-- English below</p> <p>Hi Zusammen,</p> <p>wir möchten trotz #WFH (work from home) den Community-Gedanken am Leben erhalten und liefern unser PowerShell Meetup virtuell.</p> <p>Das virtuelle Event soll möglichst interaktiv und dynamisch gestaltet werden, bringt also eure Fragen und Anregungen gerne mit.</p> <p>Den Meeting link findet ihr kurz vor Start hier auf der Seite.</p> <p>Joint uns gern auf Slack um in Kommunikation zu bleiben! <a href="https://github.com/GPSUG/Munich#slack" class="linkified">https://github.com/GPSUG/Munich#slack</a><br/>____________________________________________________________</p> <p>$Start = "19:00"<br/>____________________________________________________________</p> <p>The Sessions:</p> <p>############</p> <p>tba<br/>____________________________________________________________</p> <p>Hi,</p> <p>even during WFH (work from home) we want to keep the community spirit alive by hosting the next PowerShell meetup online.</p> <p>This virtual event is supposed to be open and interactive. Feel free to bring your questions and topics into the discussion.</p> <p>The meeting link will be posted shortly before the event on this site.</p> <p>For all updates look into the Meetup event.</p> <p>Please also consider joining us on Slack to stay in contact before and after the meetup <a href="https://github.com/GPSUG/Munich#slack" class="linkified">https://github.com/GPSUG/Munich#slack</a></p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1598878075000,
      duration: 7200000,
      id: 'dwwbxrybcmbnc',
      name: 'Foreigners Feeling Comfortable in Munich',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601485200000,
      local_date: '2020-09-30',
      local_time: '19:00',
      updated: 1600876960000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      is_online_event: false,
      group: {
        created: 1553169681000,
        name: 'Foreigners Feeling Comfortable In Munich',
        id: 31442074,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Foreigners-Feeling-Comfortable-In-Munich',
        who: 'Miembros',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Foreigners-Feeling-Comfortable-In-Munich/events/dwwbxrybcmbnc/',
      description: '<p>REGISTER HERE:<br/><a href="https://www.eventbrite.de/e/meetup-foreigners-feeling-comfortable-in-munich-tickets-122421685557" class="linkified">https://www.eventbrite.de/e/meetup-foreigners-feeling-comfortable-in-munich-tickets-122421685557</a><br/>-------------------------------------------------------------------</p> <p>Yes! After the Corona-shut-down, we can meet again! :)</p> <p>- Find new friends and surround yourself with nice people</p> <p>- Exchange experiences with people who are in the same situation</p> <p>- Get tips concerning the best café, yoga course, climbing hall, a good kindergarden, the best place to dance salsa, and all other interests and topics ….</p> <p>- Get tips around the German language and culture</p> <p>- Practice your German if you want. :)</p> <p>- Get the help of a professional, local German teacher who is guiding this group</p> <p>Let\'s connect, let\'s inspire and motivate each other!</p> <p>I’m looking forward to welcoming you!<br/>-&gt; How to find us? Ask a waiter for a table booked on "Language Success". Look for a sign with "Language Success".</p> <p>REGISTER HERE:<br/><a href="https://www.eventbrite.de/e/meetup-foreigners-feeling-comfortable-in-munich-tickets-122421685557" class="linkified">https://www.eventbrite.de/e/meetup-foreigners-feeling-comfortable-in-munich-tickets-122421685557</a></p> <p>--&gt; It\'s only possible to join with an Eventbrite-ticket.</p> <p>This is an offer of Language Success.</p> <p>Language Success supports expats to successfully learn and master the German language and cultural aspects for acting confidently like locals.</p> <p>Check out our special teaching concept which comes with practical exercises to help you apply the language to real life and cultural coaching! :-)</p> <p>www.languagesuccess.org</p> <p>—&gt; IMPORTANT: To make this event possible, please only sign up, if you’ll come and cancel your registration with time if you can\'t.<br/>—&gt; Everything is on your own bill.<br/>—&gt; Please be on time.</p> <p>--------------------------------------------------------------------<br/>REGISTER HERE:<br/><a href="https://www.eventbrite.de/e/meetup-foreigners-feeling-comfortable-in-munich-tickets-122421685557" class="linkified">https://www.eventbrite.de/e/meetup-foreigners-feeling-comfortable-in-munich-tickets-122421685557</a></p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1599120007000,
      duration: 7200000,
      id: '273001742',
      name: 'SpaceBrewery #4 w/ WARR [Student version]: From University into Space',
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1602095400000,
      local_date: '2020-10-07',
      local_time: '20:30',
      updated: 1601287006000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 40,
      is_online_event: false,
      group: {
        created: 1556824111000,
        name: 'NewSpace Brewers',
        id: 31794322,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'NewSpace-Munich',
        who: 'Astronerds',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/NewSpace-Munich/events/273001742/',
      description: '<p>🍻 SpaceBrewery is back !</p> <p>🎓 On our 4th Session, we are going to do something different. WARR students will be the stars of the evening and they will present their Workgroups and the interesting projects they are working on.</p> <p>🛰️🚀 Rocketry, satellites, exploration and space elevator are some of the Projects being carried out at the moment.<br/>Join us with a beer to know more! The event will be online and the link will be announced soon for the ones registering.</p> <p>🕒 Timeline:<br/>20h30: Beer Opening<br/>20h45: WARR Student Projects<br/>22h00: Chat time</p> <p>---</p> <p>🗣️ #SpaceBrewery, the place to engage, build and learn from the brewing NewSpace community in Munich.</p> <p>🍻 SpaceCafe is a global series of events where volunteers passionate about space curate regular speaker series covering space topics from science to business, from engineering to art. In Munich, we have Beer...so join us for #SpaceBrewery instead!</p> <p>Prost!</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1601379222000,
      duration: 7200000,
      id: '273587906',
      name: 'Koreanisch Schnupperkurs 🤓<2>',
      rsvp_limit: 5,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601568000000,
      local_date: '2020-10-01',
      local_time: '18:00',
      updated: 1601379222000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      is_online_event: false,
      group: {
        created: 1599582525000,
        name: 'Koreanisch-Deutsch Stammtisch',
        id: 34216845,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'koreanischstammtisch',
        who: '회원',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/koreanischstammtisch/events/273587906/',
      description: '<p>[ 한국어 기초1 - 초급 ]</p> <p>Hallo Leute!🌿 안녕,여러분!<br/>Diese Kurs ist dieselbe Kurs wie das Event am Dienstag.<br/>Ich würde für jeden, der interessiert ist in einer kleinen Runde einen Schnupperkurs (Lesen und Alltagsdialog) in koreanisch anbieten.</p> <p>✏️Lernmaterialien : Bleistift, Notizheft<br/>[ eigene Lernmaterialien (falls vorhanden) ]</p> <p>💡 Dieses Event ist kein professioneller Kurs. Er soll dir stattdessen einfach ein bisschen helfen, die koreanische Sprache zu erlernen. ;)</p> <p>Ich möchte dir gerne beim koreanisch lernen helfen. ✏️</p> <p>Liebe Grüße Soo 🌷</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1522694856000,
      duration: 10800000,
      id: 'lkgknpybcnbfc',
      name: 'Deutsch-Japanischer Stammtisch',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1604080800000,
      local_date: '2020-10-30',
      local_time: '19:00',
      updated: 1593250869000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      is_online_event: false,
      group: {
        created: 1512221367000,
        name: 'Deutsch-Japanischer Stammtisch',
        id: 26763059,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'deutsch-japanischer-stammtisch',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcnbfc/',
      description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1592331973000,
      duration: 3600000,
      id: 'bvxjtrybcnbcb',
      name: 'offene Meditationsgruppe - München - STARTET WIEDER VORORT',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601573400000,
      local_date: '2020-10-01',
      local_time: '19:30',
      updated: 1592331973000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 26353279,
        name: 'Sahaja Yoga Zentrum München',
        lat: 48.13126754760742,
        lon: 11.589075088500977,
        repinned: true,
        address_1: 'Am Lilienberg 2a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1405527637000,
        name: 'Free Meditation & Yoga – in Munich/München (4.400+ members)',
        id: 15760412,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Free-Meditation-Yoga-Munich',
        who: 'Meditators',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/bvxjtrybcnbcb/',
      description: '<p>STARTET WIEDER VORORT als Präsenz-Meditation!</p> <p>Einstieg ist jederzeit möglich, geeignet für Anfänger und Fortgeschrittene.</p> <p>Grundlagen und Wissen von Sahaja Yoga werden vorgestellt: Wissen über Adi Shakti, Kundalini, Energiezentren, subtile Kanäle in und einfache Reinigungstechniken mit den Elementen, die unterstützend auf unser inneres Wachstum wirken und uns ins Gleichgewicht bringen.</p> <p>Wir lernen wie wir in unserem täglichen Leben in Balance kommen und in einem Zustand der Stille Kraft schöpfen können.</p> <p>Ein zentraler Punkt ist die Stille in uns, die spürbar ist und für jeden, jederzeit zugänglich. Sie ist der Moment im Hier und Jetzt, der uns Inspiration, Freude und vieles mehr schenkt.<br/>In diesem Zustand zu verweilen bedeutet Meditation - und dann ist Platz für inneres Wachstum und Evolution.</p> <p>Jeder Abend beinhaltet auch eine geführte Meditation und auch jederzeit eine Frage-Antwort-Runde.</p> <p>Wir freuen uns auf Euch!</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '19:00',
      local_date: '2020-10-13',
      link: 'https://www.meetup.com/rice-cookie-improv/events/nfngxrybcnbrb/',
      visibility: 'public_limited',
      group: {
        created: 1468649601000,
        name: 'Rice Cookie Improvtheater in Munich',
        id: 20189476,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'rice-cookie-improv',
        who: 'Improv-Enthusiasts',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      waitlist_count: 0,
      yes_rsvp_count: 2,
      duration: 7200000,
      time: 1602608400000,
      utc_offset: 7200000,
      name: 'Get Loose with Improv',
      id: 'nfngxrybcnbrb'
    },
    {
      created: 1596390754000,
      duration: 10800000,
      id: 'qwrxxrybcnbfb',
      name: 'Come run with the MH3! ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601737200000,
      local_date: '2020-10-03',
      local_time: '17:00',
      updated: 1600791749000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      is_online_event: false,
      group: {
        created: 1436202691000,
        name: 'Munich Hash House Harriers',
        id: 18722783,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Hash-House-Harriers',
        who: 'Hashers and Harriettes',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Hash-House-Harriers/events/qwrxxrybcnbfb/',
      description: '<p>The Munich Hash House Harriers organises non-competitive "running" events every other Saturday in and around Munich.</p> <p>We run, jog or walk along a specially laid trail. Then, after a few drinks, we go for a meal (we have a car where you can leave a change of clothing). It\'s a great way to get some exercise and meet people.</p> <p>Check out our website www.munich-h3.eu.</p> <p>But right now we have suspended our "runs" because the Munich authorities have tightened the restrictions due to the increase in Covid cases.</p> <p>Keep an eye on our website and subscribe to our twitter feed @MunichH3 for updates and any alternative arrangements we may make.</p> <p>Let\'s hope the suspension is soon lifted.</p> ',
      how_to_find_us: 'To be decided',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1600374299000,
      duration: 10800000,
      fee: {
        accepts: 'cash',
        amount: 25,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: false
      },
      id: '273327963',
      name: 'Dinner at Salon Rouge',
      rsvp_limit: 6,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1605722400000,
      local_date: '2020-11-18',
      local_time: '19:00',
      updated: 1600522455000,
      utc_offset: 3600000,
      waitlist_count: 1,
      yes_rsvp_count: 6,
      venue: {
        id: 26990321,
        name: 'Salon Rouge',
        lat: 48.137596130371094,
        lon: 11.577428817749023,
        repinned: true,
        address_1: 'Burgstr. 5',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1551983247000,
        name: 'Munich Gourmets',
        id: 31331513,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Gourmets',
        who: 'Gourmets',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Gourmets/events/273327963/',
      description: '<p>We\'ll have dinner at the Salon rouge gourmet restaurant, basically the former Wernickehof (2 Michelin stars) in a new location.<br/>The 6 course degustation menu is 195€<br/><a href="http://salonrouge-muc.de/" class="linkified">http://salonrouge-muc.de/</a><br/>Please send me your food preferences (allergies, intolerances) per PM.<br/>We might reserve a second table if there is sufficient interest.</p> <p>IMPORTANT: Registration is binding and places on the reserved table are limited. I might require a 25€ deposit (to be paid per paypal in advance) from some participants which will only be refunded if you show up.<br/>Please check your PMs in the days before event for additional confirmation, extra requests and announcements.</p> ',
      how_to_find_us: 'in front of the main entrance',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1598609765000,
      duration: 7200000,
      id: 'vnpxwrybcmbnc',
      name: 'afrotanz.de',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601487900000,
      local_date: '2020-09-30',
      local_time: '19:45',
      updated: 1598609765000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25422407,
        name: 'Rudolph Steiner Schuler',
        lat: 48.156864166259766,
        lon: 11.583706855773926,
        repinned: false,
        address_1: 'Leopoldstraße 17',
        city: 'München',
        country: 'DE',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1597153092000,
        name: 'Munich Labyrynsel',
        id: 34082878,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Labyrynsel',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Labyrynsel/events/vnpxwrybcmbnc/',
      description: '<p><a href="http://www.afrotanz.de/" class="linkified">http://www.afrotanz.de/</a><br/><a href="http://cheikh-bangoura.com/taenzer.html" class="linkified">http://cheikh-bangoura.com/taenzer.html</a></p> <p>Einzelstunde: 15.- Euro (Streifenkarte 8x - 110 €)</p> <p>Ort: Turnhalle der Rudolf-Steiner-Schule Schwabing (Untergeschoss)</p> <p>Leopoldstrasse 17</p> <p>80806 München</p> <p>U-Bahn: U3 und U6 Haltestelle Giselastrasse</p> <p>Wenn Interesse besteht, immer alle aktuelle Informationen zu erhalten, schreibt uns einfach eine Email. Wir nehmen Euch in unseren Verteiler auf. Link</p> <p>Zusätzlicher offener Kurs (Kristina Prepoutsidis und Cheikh Bangoura):</p> <p>Sonntags:</p> <p>Kristina (Mittelstufe): 18.00 - 19.30 Uhr (15.- €)</p> <p>Cheikh (Fortgeschrittene) : 19.30 - 21.00 (15.- €)</p> <p>Altkatholische Kirche St. Willibrod am Sendlinger Tor in München</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1600107464000,
      duration: 5400000,
      id: '273255419',
      name: 'Co-Lunch: inspirierender Austausch & Netzwerken in der Mittagspause',
      rsvp_limit: 11,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601548200000,
      local_date: '2020-10-01',
      local_time: '12:30',
      updated: 1600107464000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 26846459,
        name: 'togather ',
        lat: 48.137943267822266,
        lon: 11.543676376342773,
        repinned: true,
        address_1: 'Schwanthalerstraße 160',
        city: 'München ',
        country: 'DE',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1538836714000,
        name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
        id: 30090989,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Co-Dining',
        who: 'Netzwerkerinnen und Netzwerker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Co-Dining/events/273255419/',
      description: '<p>Ich freue mich über jeden der Lust auf Austausch und Kommunikation hat. Auf ein herzliches Miteinander, auf gemeinsamen Genuss und einen inspirierenden Austausch.</p> <p>DISCLAIMER: Wenn du dich nicht gut fühlst, befürchtest krank zu sein oder dich nicht gut mit dem Gedanken stellst mit mehreren Menschen an einem Tisch zu sitzen, dann ist dieser Co-Lunch leider nicht für deine Teilnahmen geeignet.</p> <p>Wie immer, der Co-Lunch hat keine Agenda. Ich werde nichts moderieren. Ich biete den Raum für Gespräche und ein Miteinander.</p> <p>Eure Sarah</p> <p>P.S. Die Veranstaltung ist auf 10 Personen begrenzt. Bitte nur anmelden, wenn du tatsächlich kommst. Wenn dir doch was dazwischen kommt, bitte wieder abmelden.</p> ',
      how_to_find_us: 'am großen dreieckigen Co-Dining Tisch',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '19:00',
      local_date: '2020-10-20',
      link: 'https://www.meetup.com/rice-cookie-improv/events/nfngxrybcnbbc/',
      visibility: 'public_limited',
      group: {
        created: 1468649601000,
        name: 'Rice Cookie Improvtheater in Munich',
        id: 20189476,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'rice-cookie-improv',
        who: 'Improv-Enthusiasts',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      waitlist_count: 0,
      yes_rsvp_count: 2,
      duration: 7200000,
      time: 1603213200000,
      utc_offset: 7200000,
      name: 'Get Loose with Improv',
      id: 'nfngxrybcnbbc'
    },
    {
      created: 1593547541000,
      duration: 3600000,
      id: 'lxfwtrybcnbdb',
      name: '+Free Meditation & Yoga - CENTER RE-OPENED!  just show up – we start at 19:30h',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601659800000,
      local_date: '2020-10-02',
      local_time: '19:30',
      updated: 1593547541000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 26353279,
        name: 'Sahaja Yoga Zentrum München',
        lat: 48.13127899169922,
        lon: 11.589085578918457,
        repinned: true,
        address_1: 'Am Lilienberg 2a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1405527637000,
        name: 'Free Meditation & Yoga – in Munich/München (4.400+ members)',
        id: 15760412,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Free-Meditation-Yoga-Munich',
        who: 'Meditators',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/lxfwtrybcnbdb/',
      description: '<p>STARTET WIEDER VORORT als Präsenz-Meditation !</p> <p>Für Anfänger &amp; Fortgeschrittene, Einstieg jederzeit möglich</p> <p>With Sahaja Yoga Meditation we generally sit on chairs to achieve Yoga, effortlessly, spontaneously. As such no Asanas (exercises) are required, no mat or special clothing. We are all volunteers of a Charity organisation and have many years of experience in offering free Sahaja Yoga Meditation classes. The classes are designed to help those attending get into a genuine meditative state, which can be felt tangibly. It is quite effortless and spontaneous. The free classes feature introductory talks, video\'s, practical workshops and general question and answer opportunities, making them perfect for seekers trying to establish a state of yoga, and they are available throughout Germany.</p> <p>The idea is that you don\'t do yoga - you Achieve Yoga!</p> <p>Sahaja Yoga Meditation is a simple, time-honored technique. It helps those who enjoy it, reduce stress and increase wellness. It brings better focus and helps people become more centered and better balanced. Anyone can do it. Founded by Shri Mataji Nirmala Devi, Sahaja Yoga Meditation is a world wide movement for peace and self awakening.</p> <p>All the meetings and classes are free of any charge. Each week we go through simple meditation techniques, often with guided meditations to help reduce stress and achieve the peace of true meditation. We share tips on how to help stay in balance during the day and how to meditate at home. The meditation is based on connecting with the inner chakras (energy centres) and balancing the subtle body. The tradition and aims of meditation are explained which in essence is to be in the present with no mental activity or thoughts about the past or the future.</p> <p>Occasionally there are 1 day retreats to help those interested, deepen their individual experience and hear advice and tips from those who have been practicing for some time. It’s ultimately all about getting into ‘thoughtless awareness’, a natural state of being.</p> <p>Most of the times courses are held in German Language, but we do speak english also, some of us can also speak other languages. So don´t be shy to ask.</p> <p>Occasionally there are 1 day retreats to help those interested, deepen their individual experience and hear advice and tips from those who have been practicing for some time. It’s ultimately all about getting into ‘thoughtless awareness’, a natural state of being.</p> <p>**** ENGLISH ****</p> <p>Entdecke die Kraft die in Dir steckt!</p> <p>Herzlich Willkommen zu unseren kostenfreien Treffen. In der Sahaja Yoga Meditation sitzen wir "normal" auf Stühlen, um ohne Anstrengung und spontan das Yoga zu erreichen. Es sind keine Matten oder spezielle Kleidung notwendig.</p> <p>Die Kursleiter (Info:[masked]) sind alle ehrenamtlich für den gemeinnützigen Verein Sahaja Yoga e.V. tätig und haben mehrere Jahre Erfahrung in Sahaja Yoga Meditationskursen.</p> <p>Die Kurse sollen den Teilnehmern helfen in einen wirklichen meditativen Zustand zu kommen, der spürbar wahrgenommen werden kann. Es ist sehr spontan und ohne Anstrengung. Die Kurse beinhalten - neben einer geführten Gruppenmeditation - einführende Erklärungen, Videos, Workshops und Gelegenheiten für allgemeine Fragen und Antworten; sie sind perfekt für Sucher die den Zustand des Yoga (= gedankenfreies Bewusstsein / Tao / Sartory / Selbstverwirklichung ...) erreichen wollen.</p> <p>The idea is that you don\'t do yoga - YOU ACHIEVE YOGA!</p> <p>Die Kurse finden in der Regel in deutscher Sprache statt. Bei Bedarf können wir englisch - teilweise auch andere Sprachen.</p> <p>Spontanes Kommen ist möglich, für uns wäre es zum planen gut, wenn ihr hier euer Kommen anmelden würdet.</p> <p>**** Über unser subtiles Sytem ****</p> <p>In jedem Menschen ist ein subtiles System aus Energiezentren (Chakren) und Kanälen (Nadis) angelegt. Es beeinflusst unser körperliches, emotionales, seelisches und geistiges Wohlbefinden, also alle Aspekte unseres Seins. Jedes Chakra ist mit bestimmten menschlichen Eigenschaften und Fähigkeiten verbunden.</p> <p>Durch die Meditation in Sahaja Yoga wird eine in uns schlafende Energie (Kundalini) erweckt. Diese mütterliche Kraft reinigt unsere Chakren und löst Blockaden. Unsere Stärken werden immer stärker und unsere Schwächen werden immer schwächer. Sahaja Yoga ist eine einfache, leicht zu erlernende Meditation. Sie hilft uns, zu entspannen, uns gut zu fühlen und gibt uns unsere innere Balance.</p> <p>Im ersten Satz der UNESCO-Verfassung steht: „Da Kriege im Geist der Menschen entstehen, muss auch der Frieden im Geist der Menschen verankert werden.“ Deshalb ist Sahaja Yoga ein Partner des UNESCO Center for Peace.</p> <p>Die Wechselwirkung zwischen Geist und Körper wird immer mehr erforscht. Wissenschaftliche Studien zeigen, dass regelmäßige Meditation die Gesundheit verbessert. Zum Beispiel gibt es positive Effekte bei Burnout, Depression, Schlaflosigkeit, ADHS, Asthma und bei vielen anderen Problemen. Ängste werden reduziert, die Konzentration gesteigert und die Lebensfreude erhöht.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '19:00',
      local_date: '2020-10-06',
      link: 'https://www.meetup.com/rice-cookie-improv/events/nfngxrybcnbjb/',
      visibility: 'public_limited',
      group: {
        created: 1468649601000,
        name: 'Rice Cookie Improvtheater in Munich',
        id: 20189476,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'rice-cookie-improv',
        who: 'Improv-Enthusiasts',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      waitlist_count: 0,
      yes_rsvp_count: 2,
      duration: 7200000,
      time: 1602003600000,
      utc_offset: 7200000,
      name: 'Get Loose with Improv',
      id: 'nfngxrybcnbjb'
    },
    {
      created: 1596390754000,
      duration: 10800000,
      id: 'qwrxxrybcnbwb',
      name: 'Come run with the MH3! ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1602946800000,
      local_date: '2020-10-17',
      local_time: '17:00',
      updated: 1600791749000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1436202691000,
        name: 'Munich Hash House Harriers',
        id: 18722783,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Hash-House-Harriers',
        who: 'Hashers and Harriettes',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Hash-House-Harriers/events/qwrxxrybcnbwb/',
      description: '<p>The Munich Hash House Harriers organises non-competitive "running" events every other Saturday in and around Munich.</p> <p>We run, jog or walk along a specially laid trail. Then, after a few drinks, we go for a meal (we have a car where you can leave a change of clothing). It\'s a great way to get some exercise and meet people.</p> <p>Check out our website www.munich-h3.eu.</p> <p>But right now we have suspended our "runs" because the Munich authorities have tightened the restrictions due to the increase in Covid cases.</p> <p>Keep an eye on our website and subscribe to our twitter feed @MunichH3 for updates and any alternative arrangements we may make.</p> <p>Let\'s hope the suspension is soon lifted.</p> ',
      how_to_find_us: 'To be decided',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1522694856000,
      duration: 10800000,
      id: 'lkgknpybcqbhc',
      name: 'Deutsch-Japanischer\u00ad Stammtisch',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1608919200000,
      local_date: '2020-12-25',
      local_time: '19:00',
      updated: 1522694856000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1512221367000,
        name: 'Deutsch-Japanischer Stammtisch',
        id: 26763059,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'deutsch-japanischer-stammtisch',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcqbhc/',
      description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1596390754000,
      duration: 10800000,
      id: 'qwrxxrybcnbpc',
      name: 'Come run with the MH3! ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1604160000000,
      local_date: '2020-10-31',
      local_time: '17:00',
      updated: 1600791749000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      is_online_event: false,
      group: {
        created: 1436202691000,
        name: 'Munich Hash House Harriers',
        id: 18722783,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Hash-House-Harriers',
        who: 'Hashers and Harriettes',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Hash-House-Harriers/events/qwrxxrybcnbpc/',
      description: '<p>The Munich Hash House Harriers organises non-competitive "running" events every other Saturday in and around Munich.</p> <p>We run, jog or walk along a specially laid trail. Then, after a few drinks, we go for a meal (we have a car where you can leave a change of clothing). It\'s a great way to get some exercise and meet people.</p> <p>Check out our website www.munich-h3.eu.</p> <p>But right now we have suspended our "runs" because the Munich authorities have tightened the restrictions due to the increase in Covid cases.</p> <p>Keep an eye on our website and subscribe to our twitter feed @MunichH3 for updates and any alternative arrangements we may make.</p> <p>Let\'s hope the suspension is soon lifted.</p> ',
      how_to_find_us: 'To be decided',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1600986914000,
      duration: 7200000,
      id: '273490486',
      name: 'Social Dinner | OKTOBERFEST Edition',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601658000000,
      local_date: '2020-10-02',
      local_time: '19:00',
      updated: 1600986914000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26846459,
        name: 'togather ',
        lat: 48.137943267822266,
        lon: 11.543676376342773,
        repinned: true,
        address_1: 'Schwanthalerstraße 160',
        city: 'München ',
        country: 'DE',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1538836714000,
        name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
        id: 30090989,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Co-Dining',
        who: 'Netzwerkerinnen und Netzwerker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Co-Dining/events/273490486/',
      description: '<p>Unser Social Dinner goes Oktoberfest.</p> <p>Wer Lust daran hat kann an diesem Abend gerne in Tracht kommen. Auf der Speisekarte gibt es zusätzlich eine paar Oktoberfestschmankerl.</p> <p>Ich freue mich auf dich.</p> <p>WAS IST SOCIAL DINNER?<br/>Gutes Essen genießen und ein geselliges Miteinander erleben. Wer dabei sein möchte bitte anmelden.</p> <p>WAS DICH ERWARTET:<br/>Ich bin Gastgeberin aus Leidenschaft und glaube, dass wir zusammen mehr erreichen können. Zu diesem Zweck habe ich das togather Anfang des Jahres eröffnet.</p> <p>Wünscht du dir in einer Wohlfühlatmosphäre genussvoll und in Muße speisen zu können?</p> <p>Willst du dich in einem geselligen Rahmen mit Gleichgesinnten austauschen und dein soziales wie berufliches Netzwerk erweitern?</p> <p>Im togather lernst du neue interessante Menschen kennen, führst vielseitige Gespräche und gehst anschließend beschwingt und motiviert in deinen Tag zurück. Du gewinnst Lebensqualität durch liebevoll zubereitetes Essen in gemütlicher Atmosphäre.</p> <p>Klingt das gut? Dann bis Freitag!</p> ',
      how_to_find_us: 'am großen Community Table in der Restaurant Mitte',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1522694856000,
      duration: 10800000,
      id: 'lkgknpybcpbkc',
      name: 'Deutsch-Japanischer\u00ad Stammtisch',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1606500000000,
      local_date: '2020-11-27',
      local_time: '19:00',
      updated: 1522694856000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      is_online_event: false,
      group: {
        created: 1512221367000,
        name: 'Deutsch-Japanischer Stammtisch',
        id: 26763059,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'deutsch-japanischer-stammtisch',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcpbkc/',
      description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
};

export { mockEvents };